# Santosh's awesome gemfile with Casks

gem "bigdecimal"
gem "bundler"
gem "bundler-unload"
gem "erubis"
gem "executable-hooks"
gem "facter"
gem "gem-wrappers"
gem "io-console"
gem "json"
gem "jsonlint"
gem "librarian-puppet"
gem "minitest"
gem "netaddr"
gem "oj"
gem "psych"
gem "puppet"
gem "rainbow"
gem "rake"
gem "rdoc"
gem "require"
gem "rubygems-bundler"
gem "rvm"
gem "sass"
gem "scss_lint"
gem "test-unit"
gem "thor"
gem "tmuxinator"
gem "awesome_print", require:"ap"
gem "peek"
gem "newrelic_rpm"
