#!/usr/bin/env sh

# mission-control desktop labels
yabai -m space 1 --label web
yabai -m space 2 --label terminal
yabai -m space 3 --label code
yabai -m space 4 --label social
yabai -m space 5 --label notes
yabai -m space 6 --label mail
yabai -m space 7 --label media
yabai -m space 8 --label games

# window rules
yabai -m rule --add app="^Arc$" space=web
yabai -m rule --add app="^Kitty$" space=terminal
yabai -m rule --add app="^Visual Studio Code$" space=code
yabai -m rule --add app="^IntelliJ IDEA Ultimate$" space=code
yabai -m rule --add app="^Messages$" space=social
yabai -m rule --add app="^Slack$" space=social
yabai -m rule --add app="^Discord$" space=social grid=1:1:0:0:1:1 manage=off
yabai -m rule --add app="^Notion$" space=notes
yabai -m rule --add app="^Notes$" space=notes
yabai -m rule --add app="^Spark Desktop$" space=mail
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^(Activity Monitor|Archive Utility|Calculator|Finder|QuickTime Player|System Preferences|System Settings)$" manage=off
yabai -m rule --add app="^Steam$" space=games manage=off

JB_Apps='^(CLion|PyCharm|IntelliJ IDEA|IntelliJ IDEA Ultimate)$'
yabai -m rule --add app="${JB_Apps}" manage=off
# If `Open last project when launch` is checked, add this rule. And make sure `always show project path` is also checked.
# yabai -m rule --add app="${JB_Apps}" title=".*\[.*\].*" manage=on
yabai -m rule --add app="${JB_Apps}" title="^$"  manage=on

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# global settings
yabai -m config                              \
    mouse_follows_focus         on           \
    focus_follows_mouse         autoraise    \
    window_placement            second_child \
    split_type                  auto         \
    top_padding                 7           \
    left_padding                7           \
    right_padding               7           \
    bottom_padding              7           \
    window_gap                  7           \
    layout                      bsp          \
    mouse_modifier              fn           \
    mouse_action1               move         \
    mouse_action2               resize       \
    mouse_drop_action           swap

echo "yabai configuration loaded.."
